# Generated by Django 4.1.2 on 2022-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ariza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
