# Generated by Django 4.1.2 on 2022-10-11 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_ariza_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
