# Generated by Django 4.1.2 on 2022-10-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_coursefacts_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefacts',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='teacherfacts',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
