# Generated by Django 4.1.2 on 2022-10-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_loyihalarfacts_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
