# Generated by Django 4.1.2 on 2022-10-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
