# Generated by Django 4.1.2 on 2022-10-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_ariza_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglist',
            name='tartib_raqami',
            field=models.SmallIntegerField(default=0),
        ),
    ]
