# Generated by Django 4.1.2 on 2022-10-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_learninglist_tartib_raqami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglist',
            name='tartib_raqami',
            field=models.SmallIntegerField(),
        ),
    ]
