# Generated by Django 4.1.2 on 2022-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='bot_token',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
