# Generated by Django 4.1.2 on 2022-10-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_admin_bot_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='bot_token',
            field=models.CharField(max_length=100),
        ),
    ]
